// <auto-generated />
using System;
using BankingReconciliation.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BankingReconciliation.Api.Data.Migrations
{
    [DbContext(typeof(ReconciliationDbContext))]
    [Migration("20260710161520_InitialPostgresSchema")]
    partial class InitialPostgresSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BankingReconciliation.Api.Data.ReconciliationBatchEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BankFileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)");

                    b.Property<string>("BranchFileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MatchedCount")
                        .HasColumnType("integer");

                    b.Property<int>("MismatchCount")
                        .HasColumnType("integer");

                    b.Property<int>("OnlyInBankCount")
                        .HasColumnType("integer");

                    b.Property<int>("OnlyInBranchCount")
                        .HasColumnType("integer");

                    b.Property<int>("TotalBankRecords")
                        .HasColumnType("integer");

                    b.Property<int>("TotalBranchRecords")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.ToTable("ReconciliationBatches", (string)null);
                });

            modelBuilder.Entity("BankingReconciliation.Api.Data.ReconciliationDifferenceEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("AmountDifference")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("BankAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("BankQuantity")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<DateOnly?>("BankTransactionDate")
                        .HasColumnType("date");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("BranchAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("BranchCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<decimal?>("BranchQuantity")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<DateOnly?>("BranchTransactionDate")
                        .HasColumnType("date");

                    b.Property<string>("FundCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<decimal?>("QuantityDifference")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("TransactionNumber")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.HasIndex("Status");

                    b.HasIndex("BatchId", "BranchCode", "FundCode", "TransactionNumber")
                        .IsUnique();

                    b.ToTable("ReconciliationDifferences", (string)null);
                });

            modelBuilder.Entity("BankingReconciliation.Api.Data.ReconciliationDifferenceEntity", b =>
                {
                    b.HasOne("BankingReconciliation.Api.Data.ReconciliationBatchEntity", "Batch")
                        .WithMany("Differences")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");
                });

            modelBuilder.Entity("BankingReconciliation.Api.Data.ReconciliationBatchEntity", b =>
                {
                    b.Navigation("Differences");
                });
#pragma warning restore 612, 618
        }
    }
}
